version: '3.9'

services:
  web:
    build: .
    container_name: p_web
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    environment:
      - "DJANGO_DEBUG=True"
      - "DJANGO_ALLOWED_HOSTS=['localhost', '127.0.0.1']"
      - "DJANGO_SECRET_KEY=django-insecure-(z*e&64amq_bz)6jujnfcqm+y)080%hy2#as-&3mu8ctgsh!e8"
    ports:
      - '8001:8001'
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db:

